// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesHub.Database;

#nullable disable

namespace MoviesHub.Migrations
{
    [DbContext(typeof(MovieHubContext))]
    partial class MovieHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("MoviesHub.Entities.Cinema", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.ToTable("Cinema");
                });

            modelBuilder.Entity("MoviesHub.Entities.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("princessTheatreMovieId")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<DateOnly>("releaseDate")
                        .HasColumnType("date");

                    b.Property<int>("runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("synopsis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MoviesHub.Entities.MovieCinema", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cinemaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("movieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("showTime")
                        .HasColumnType("date");

                    b.Property<decimal>("ticketPrice")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("id");

                    b.HasIndex("cinemaId");

                    b.HasIndex("movieId");

                    b.ToTable("MovieCinema");
                });

            modelBuilder.Entity("MoviesHub.Entities.MovieReview", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("movieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("reviewDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("score")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("id");

                    b.HasIndex("movieId");

                    b.ToTable("MovieReview");
                });

            modelBuilder.Entity("MoviesHub.Entities.MovieCinema", b =>
                {
                    b.HasOne("MoviesHub.Entities.Cinema", "cinema")
                        .WithMany()
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesHub.Entities.Movie", "movie")
                        .WithMany("movieCinemas")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cinema");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("MoviesHub.Entities.MovieReview", b =>
                {
                    b.HasOne("MoviesHub.Entities.Movie", "movie")
                        .WithMany("movieReviews")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");
                });

            modelBuilder.Entity("MoviesHub.Entities.Movie", b =>
                {
                    b.Navigation("movieCinemas");

                    b.Navigation("movieReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
